#!/bin/bash
to_dec(){d=0;l=${#2};for((i=0;i<${#1};i++));do c="${1:$i:1}";d=$((d*l + $(expr index "$2" "$c") -1));done;echo $d;}; from_dec(){d=$1;b=$2;r="";l=${#b};[[ $d -eq 0 ]] && { echo "${b:0:1}"; return; }; while [ $d -gt 0 ]; do r="${b:$((d%l)):1}$r"; d=$((d/l)); done; echo $r;}; from_dec $(( $(to_dec "$WATER" "water") + $(to_dec "$STIR" "stir") )) "bestchol"
